#!/bin/sh

activity=pvcmove

TS=$(/bin/date +%s)
short_date=$(/bin/date +%m%d%y%H%M)
DLOG="${HOME}/pvcmove-debug.${$}.${short_date}.log"
LOG="${HOME}/pvcmove.${$}.log"
exec 100>>${DLOG}
BASH_XTRACEFD=100
set -x
date -u

if [ -z "${1}" ]; then
  echo "Need project name"
  set +xv
  exit 1
fi

if [ -z "${2}" ]; then
  oc -n ${1} get pvc --no-headers
  echo "Need pv claim name"
  set +xv
  exit 1
fi

if [ -z "${3}" ]; then
  echo "Need new pv claim class" 
  set +xv
  exit 1
fi

project="${1}"
pvcname="${2}"
pvcclass="${3}"

case ${project} in
  *-che)
    service=che
    ;;
  *-jenkins)
    service=jenkins
    ;;
  *-run)
    service=run
    ;;
  *-stage)
    service=stage
    ;;
  *)
    service=build
    ;;
esac
tenant=$(echo ${project} | sed -e 's/\(-jenkins$\|-che$\|-run$\|-stage$\)//')

function log () {
  echo "`date -u` (${project}:${pvcname}:${action}) ${*}" | tee -a ${LOG}
}
function logsentry () {
    if [ ! -z "${SENTRY_DSN}" ]; then
      sentry-cli send-event --logfile ${LOG} --message "${1}" --tag pvcname:${pvcname} --tag project:${project} --tag tenant:${tenant} --tag service:${service} --no-environ
    fi
}

function do_debug () {
  #echo "########### ${project}:events"
  #oc -n ${project} get events | tail -n5
 
  log "######DEBUG###### ${project}:dc,rc,po,pvc"
  OUT=$(echo xxx;oc -n ${project} get dc,rc,po,pvc -o wide --no-headers)
  log "${OUT}"
}

function statuscheck () {
  if [ ${1} -ne 0 ]; then
    log "Non-zero (${1}) return, check debug log ${DLOG}, application log ${LOG}."
    logsentry "Command returned error, exiting"
    exit 1
  else
    log "Command returned success"
  fi
}

function get_dcversion () {
  dcname="${1}"
  log "Getting latested dc version for dc/${dcname}"
  OUT=$(oc -n ${project} get dc/${dcname} -o jsonpath='{.status.latestVersion}')
  statuscheck $?
  log "Latest version: ${OUT}"
}

function add_movedc () {
  dcname="$1"
  src="$2"
  dst="$3"
  log "Adding dc/${dcname} with mounts source:${src} and destination:${dst}"
  oc process -f pvcmove.template.yml -p TEMPLATE_NAME=${dcname} -p SOURCE_VOLUME=${src} -p DEST_VOLUME="${dst}" | oc -n ${project} create -f - 2>&1
  statuscheck $?
  oc -n ${project} rollout resume dc/${dcname} 2>&1
  statuscheck $?
  LATEST_DC=$(get_dcversion ${dcname})
}

function del_movedc () {
  dcname="$1"
  log "Removing dc/${dcname}"
  oc -n ${project} delete dc/${dcname} 2>&1
  statuscheck $?
}

function add_pvc () {
  pvc="$1"
  log "Adding pvc/${pvc} to project/${project}"
  oc process -f new_pvc.template.yml -p PVC_NAME="${pvc}" -p STORAGE_CLASS=${pvcclass} | oc -n ${project} create -f - 2>&1
  statuscheck $?
  log "Verifying: pvc/${pvc} is added"
  ADDED=no
  while [ "${ADDED}" == "no" ]; do
    OUT=$(oc -n ${project} get pvc/${pvc})
    [ $? -eq 0 ] && ADDED="yes"
    sleep 1
  done
  log "${OUT}"
  log "Confirmed: pvc/${pvc} is present"
}

function del_pvc () {
  pvc="$1"
  log "Removing pvc/${pvc}"
  oc -n ${project} delete pvc/${pvc} 2>&1 
  statuscheck $?
  if [ ! -z "${2}" ] && [ "${2}" == "wait" ]; then
    log "Verifying: pvc/${pvc} is absent"
    REMOVED=no
    while [ "${REMOVED}" == "no" ]; do
      OUT=$(oc -n ${project} get pvc/${pvc})
      [ $? -eq 0 ] || REMOVED="yes"
      sleep 1
    done
    log "${OUT}"
    log "Confirmed: pvc/${pvc} is absent"
  fi 
}

function check_dc () {
  dcname="$1"
  pvctimeout=300
  log "Making sure dc/${dcname} has available replicas"
  COUNT=0
  while [ ${COUNT} -lt ${pvctimeout} ]; do
    echo -n "."
    rctotal=$(oc -n ${project} get dc/pvcmove -ojsonpath='{.status.availableReplicas}')
    if [ "${rctotal}" != "0" ]; then
      echo " Success!"
      log "Replicas running for dc/${dcname}"
      sleep 1
      break
    fi
    sleep 1
    COUNT=$((${COUNT}+1))
  done
  if [ ${COUNT} -gt ${pvctimeout} ]; then
    echo " Timeout!"
    log "Timeout waiting for dc/${dcname} to come on-line"
    statuscheck 1
  else 
    log "dc/${dcname} is now on-line"
  fi
  log "Making sure po/${dcname}- not in Terminating state"
  COUNT=0
  while [ ${COUNT} -lt ${pvctimeout} ]; do
    echo -n "."
    isterminating=$(oc -n ${project} get po -ldeploymentconfig=${dcname} --no-headers|egrep -q Termin;echo $?)
    if [ "${isterminating}" == "0" ]; then
      echo " Success!"
      log "Pods not terminating for dc/${dcname}"
      sleep 1
      break
    fi
    sleep 1
    COUNT=$((${COUNT}+1))
  done
  if [ ${COUNT} -gt ${pvctimeout} ]; then
    echo " Timeout!"
    log "Timeout waiting for po/${dcname} to not be Terminating"
    statuscheck 1
  else 
    log "dc/${dcname} is now on-line"
  fi
}

function check_runningpods () {
  log "Verifying: Are pods running in project/${project}?"
  podcount=$(oc -n ${project} get po --no-headers | wc -l)
  if [ "${podcount}" -gt "0" ]; then
    log "Pods (${podcount}) are active for ${project}, terminating"
    logsentry "Pods (${podcount}) are active for ${project}, retry later"
    set +xv
    echo "# app: ${LOG}"
    echo "# debug: ${DLOG}"
    exit 0
  fi
  log "Confirmed: No pods are running in project/${project}"
}     


function check_pvcusage () {
  dcname="$1"
  src="$2"
  log "Checking usage of ${src} in dc/${dcname} active pod"
  OUT=$(oc -n ${project} rsh --shell=/bin/bash --timeout=180 dc/${dcname} /usr/sbin/du-osio ${src})
  ERR=$?
  log "${OUT}"
  statuscheck ${ERR}
}

function rsync_pvc () {
  dcname="$1"
  src="$2"
  dst="$3"
  log "Grabbing volume info for dc/${dcname}"
  OUT=$(oc -n ${project} volume dc/${dcname})
  log "${OUT}"
  log "Copying from ${src} to ${dst} through dc/${dcname}"
  OUT=$(oc -n ${project} rsh --shell=/bin/bash --timeout=180 dc/${dcname} /usr/sbin/rsync-osio ${src} ${dst})
  ERR=$?
  log "${OUT}"
  if [ ${ERR} -ne 23 ]; then
    statuscheck ${ERR}
  fi
}

function add_copysemaphore () {
  dcname="$1"
  semfile="$2"
  log "Adding ${semfile} to dc/${dcname}"
  OUT=$(oc -n ${project} rsh --shell=/bin/bash --timeout=180 dc/${dcname} /usr/bin/touch ${semfile})
  ERR=$?
  log "${OUT}"
  if [ ${ERR} -ne 0 ]; then
    statuscheck ${ERR}
  fi
}

function check_copysemaphore () {
  dcname="$1"
  semfile="$2"
  log "Checking for ${semfile} in dc/${dcname}"
  OUT=$(oc -n ${project} rsh --shell=/bin/bash --timeout=180 dc/${dcname} /bin/ls -la ${semfile})
  ERR=$?
  log "${OUT}"
  if [ ${ERR} -ne 0 ]; then
    statuscheck ${ERR}
  fi
}

function update_quota () {
  log "Increasing pvc hard limit quota for project/${project}"
  case ${service} in
   che)
     pvclimit=4
     ;;
   jenkins)
     pvclimit=5
     ;;
   *)
     pvclimit=3
     ;;
  esac
  oc -n ${project} patch quota object-counts -p '{"spec":{"hard":{"persistentvolumeclaims":"'${pvclimit}'"}}}'
  statuscheck $?
}

function reset_quota () {
  log "Restoring pvc hard limit quota for project/${project}"
  case ${service} in
   che)
     pvclimit=2
     ;;
   jenkins)
     pvclimit=3
     ;;
   *)
     pvclimit=1 
     ;;
  esac
  oc -n ${project} patch quota object-counts -p '{"spec":{"hard":{"persistentvolumeclaims":"'${pvclimit}'"}}}'
  statuscheck $?
}

log "Begin pvc move for project \"${project}\", pvc \"${pvcname}\" to class \"${pvcclass}\""

action="Check for running pods"
check_runningpods

action="Update quota"
update_quota 
action="Create temp PVC"
add_pvc temp-${pvcname}
action="Add temp copy DC"
add_movedc pvcmove ${pvcname} temp-${pvcname}
action="Verify DC spun up"
check_dc pvcmove
### debugging
do_debug
action="Check PVC usage"
check_pvcusage pvcmove /source

action="Add semaphore to originating PVC source"
add_copysemaphore pvcmove /source/.sync.${TS}

action="Copy data to temp PVC"
rsync_pvc pvcmove /source/ /dest
### debugging
do_debug
action="Remove temp copy DC"
del_movedc pvcmove

action="Remove original PVC"
del_pvc ${pvcname} wait
### debugging
do_debug

action="Add new PVC"
add_pvc ${pvcname}
action="Add new copy DC"
add_movedc pvcmove temp-${pvcname} ${pvcname}
action="Verify DC spun up"
check_dc pvcmove
### debugging
do_debug

action="Copy data to new PVC"
rsync_pvc pvcmove /source/ /dest

action="Check semaphore on temp PVC source"
check_copysemaphore pvcmove /source/.sync.${TS}

action="Check semaphore on new PVC target"
check_copysemaphore pvcmove /dest/.sync.${TS}

action="Remove new copy DC"
del_movedc pvcmove
### debugging
do_debug
action="Remove temp PVC"
del_pvc temp-${pvcname} wait
### debugging
do_debug
action="Restore quota"
reset_quota

log "Completed pvc move for project \"${project}\", pvc \"${pvcname}\" to class \"${pvcclass}\""

logsentry "Completed pvc move"

set +xv
echo "# app log: ${LOG}"
echo "# debug log: ${DLOG}"
